// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class IMSystemMsgInfo;
@class IMSystemMsgInfoBuilder;



@interface ImsystemRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define IMSystemMsgInfo_from_user_id @"fromUserId"
#define IMSystemMsgInfo_to_user_id @"toUserId"
#define IMSystemMsgInfo_addition_msg @"additionMsg"
#define IMSystemMsgInfo_attach_data @"attachData"
@interface IMSystemMsgInfo : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasAdditionMsg_:1;
  BOOL hasAttachData_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  NSData* additionMsg;
  NSData* attachData;
  UInt32 fromUserId;
  UInt32 toUserId;
}
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasAdditionMsg;
- (BOOL) hasAttachData;
@property (readonly) UInt32 fromUserId;
@property (readonly) UInt32 toUserId;
@property (readonly, strong) NSData* additionMsg;
@property (readonly, strong) NSData* attachData;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (IMSystemMsgInfoBuilder*) builder;
+ (IMSystemMsgInfoBuilder*) builder;
+ (IMSystemMsgInfoBuilder*) builderWithPrototype:(IMSystemMsgInfo*) prototype;
- (IMSystemMsgInfoBuilder*) toBuilder;

+ (IMSystemMsgInfo*) parseFromData:(NSData*) data;
+ (IMSystemMsgInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMSystemMsgInfo*) parseFromInputStream:(NSInputStream*) input;
+ (IMSystemMsgInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (IMSystemMsgInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (IMSystemMsgInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface IMSystemMsgInfoBuilder : PBGeneratedMessageBuilder {
@private
  IMSystemMsgInfo* resultImsystemMsgInfo;
}

- (IMSystemMsgInfo*) defaultInstance;

- (IMSystemMsgInfoBuilder*) clear;
- (IMSystemMsgInfoBuilder*) clone;

- (IMSystemMsgInfo*) build;
- (IMSystemMsgInfo*) buildPartial;

- (IMSystemMsgInfoBuilder*) mergeFrom:(IMSystemMsgInfo*) other;
- (IMSystemMsgInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (IMSystemMsgInfoBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromUserId;
- (UInt32) fromUserId;
- (IMSystemMsgInfoBuilder*) setFromUserId:(UInt32) value;
- (IMSystemMsgInfoBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (UInt32) toUserId;
- (IMSystemMsgInfoBuilder*) setToUserId:(UInt32) value;
- (IMSystemMsgInfoBuilder*) clearToUserId;

- (BOOL) hasAdditionMsg;
- (NSData*) additionMsg;
- (IMSystemMsgInfoBuilder*) setAdditionMsg:(NSData*) value;
- (IMSystemMsgInfoBuilder*) clearAdditionMsg;

- (BOOL) hasAttachData;
- (NSData*) attachData;
- (IMSystemMsgInfoBuilder*) setAttachData:(NSData*) value;
- (IMSystemMsgInfoBuilder*) clearAttachData;
@end


// @@protoc_insertion_point(global_scope)
