package com.tenth.space.DB.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import java.io.Serializable;

/**
 * Entity mapped to table Blog.
 */
public class BlogEntity implements Serializable {

    private Long id;
    private int blogId;
    private String blogText;
    private String blogAudio;
    private String blogImages;
    private String avatarUrl;
    private String nickName;
    private Integer commentCnt;
    private Integer likeCnt;
    private Long writerUserId;
    public int isFollow = 0;
    private long created;
    private long updated;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BlogEntity() {
    }

    public BlogEntity(Long id) {
        this.id = id;
    }

    public BlogEntity(Long id, int blogId, String blogText, String blogAudio, String blogImages, String avatarUrl, String nickName, Integer commentCnt, Integer likeCnt, Long writerUserId, int created, int updated) {
        this.id = id;
        this.blogId = blogId;
        this.blogText = blogText;
        this.blogAudio = blogAudio;
        this.blogImages = blogImages;
        this.avatarUrl = avatarUrl;
        this.nickName = nickName;
        this.commentCnt = commentCnt;
        this.likeCnt = likeCnt;
        this.writerUserId = writerUserId;
        this.created = created;
        this.updated = updated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getBlogId() {
        return blogId;
    }

    public void setBlogId(int blogId) {
        this.blogId = blogId;
    }

    public String getBlogText() {
        return blogText;
    }

    public void setBlogText(String blogText) {
        this.blogText = blogText;
    }

    public String getBlogAudio() {
        return blogAudio;
    }

    public void setBlogAudio(String blogAudio) {
        this.blogAudio = blogAudio;
    }

    public String getBlogImages() {
        return blogImages;
    }

    public void setBlogImages(String blogImages) {
        this.blogImages = blogImages;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Integer getCommentCnt() {
        return commentCnt;
    }

    public void setCommentCnt(Integer commentCnt) {
        this.commentCnt = commentCnt;
    }

    public Integer getLikeCnt() {
        return likeCnt;
    }

    public void setLikeCnt(Integer likeCnt) {
        this.likeCnt = likeCnt;
    }

    public Long getWriterUserId() {
        return writerUserId;
    }

    public void setWriterUserId(Long writerUserId) {
        this.writerUserId = writerUserId;
    }

    public long getCreated() {
        return created;
    }

    public void setCreated(long created) {
        this.created = created;
    }

    public long getUpdated() {
        return updated;
    }

    public void setUpdated(int updated) {
        this.updated = updated;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
